import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/index.module.css";
import Link from "next/link";
import { useRouter } from "next/router";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export default function Home() {
	const router = useRouter();
	return (
		<>
			<style jsx>{`
				button {
					background-color: blue;
					color: white;
					padding: 10px;
          cursor:pointer;
          margin:0px 10px
				}
			`}</style>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<div className={styles.mainContainer}>
					<Link href={"/about"}>
						about
					</Link>
					<button
						onClick={() => {
							router.push("/about");
						}}>
						navigate to about{" "}
					</button>
					<h2>
						<Link href={"/serverANDclient"}>
							compare server side and client side
						</Link>
					</h2>
				</div>
			</main>
		</>
	);
}
