import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { useRouter } from "next/router";
import { indexStyles } from "@/styles/indexStyled";
import Banner from "@/components/banner";
import Header from "@/components/header";
import Contact from "./contact";
import Applayout from "@/layouts/applayout";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export default function Home() {
	const router = useRouter();
	return (
		<>
			<style jsx>{`
				button {
					background-color: blue;
					color: white;
					padding: 10px;
					cursor: pointer;
					margin: 0px 10px;
				}
			`}</style>
			<style jsx>{indexStyles}</style>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</>
	);
}
